# Single vs MultiDimensional Arrays

In [11]:
import numpy as np

In [12]:
array = np.array([0,1,2,3,4,5]) # 1 Dimensional Array
print("1D_Array:", array.shape)

array_2D = array[:, np.newaxis] # 2 Dimensional Array
print("2D_Array:", array_2D.shape)

array_3D = array[:, np.newaxis, np.newaxis] # 3 Dimensional Array
print("3D_Array:", array_3D.shape)

array_4D = array[:, np.newaxis, np.newaxis, np.newaxis] # 4 Dimensional Array
print("4D_Array:", array_4D.shape)

1D_Array: (6,)
2D_Array: (6, 1)
3D_Array: (6, 1, 1)
4D_Array: (6, 1, 1, 1)


In [13]:
squeeze_array = np.squeeze(array[:, np.newaxis, np.newaxis])
squeeze_array.shape

"""Converts Into A One Dimensional Array"""

'Converts Into A One Dimensional Array'

In [14]:
print(array)

[0 1 2 3 4 5]


In [15]:
print(array_2D)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [16]:
print(array_2D.T) 

[[0 1 2 3 4 5]]


The (length,) array is an array where each element is a number and there are length elements in the array. The (length, 1) array is an 2-D array which also has length elements, but each element itself is its own array with a single element. 

https://www.oreilly.com/ideas/intro-to-scikit-learn
- Target Array

https://processing.org/tutorials/2darray/
- First Paragraph

(Length,) ~ We typically want to work with 1-Dimensional Target Arrays Which Have Continuous Numerical Values or Discrete Variables For Classes/Labels. 
- We can imagine a 1-D Target Array As A List Of Foods That We Eat. An example would be: 
[Pizza, Salad, Ice-Cream, Chicken, Potatoes, Noodles]
- For 2D Arrays We Can Imagine A List Within A List:
[[Pizza and Salad], [Ice-Cream and Chicken], [Potatoes and Noodles]]

Working With Anymore Dimensions Will Be Difficult To Visualize Because Our Computer Screen Is
Only 2 Dimensional

# List In List Matrix

In [18]:
from scipy import sparse

In [19]:
'''CSR Representation Is Efficient For Computations, But Not Efficient For Adding Elements. \
Using The Lil (List-In-List) Representation Is Better'''

# Creating An Empty List-in-List (LIL) Matrix And Adding Items In A 7 x 7 Size Array.
# sparse.lil_matrix ~ Create A Sparse Matrix For A List in List
list_in_list = sparse.lil_matrix((3,3))

# Sample Out Random Element Values At And Between Low Int And High Int And Draw Out A Random X by 2 Matrix
for i, j in np.random.randint(0, 3, (5, 2)): # Shape Of list_in_list
    list_in_list[i, j] = i + j       


print (list_in_list)

# Converts our LIL with Elements To An Array
print (list_in_list.toarray())

  (0, 1)	1.0
  (1, 2)	3.0
  (2, 0)	2.0
  (2, 2)	4.0
[[ 0.  1.  0.]
 [ 0.  0.  3.]
 [ 2.  0.  4.]]


List_in_List Matrix

- sparse.lil_matrix((nrows,npoints)) ~ 

- For list_in_list: Creates An Empty List in List With nrows and npoints. This Will Create A Matrix With All Zeros. Then We Want To Add Random Elements Into Our Matrix. For i In Range (0, nrows) Of Our Empty Matrix, Use Random Positions In Our Matrix And Assign New Created Values To Them From j

- For j (x,2_Columns), x Determines How Many Random Values We Want To Create: j Represents The Random Value (Other Than Zero) Inside The Matrix
- For i In Range Int_Low, Int_High, Draw Random Positions In Matrix: i Represents The Position Of A Point Inside The Matrix
- random.randint Creates Random Values Inside Our Matrix